[package]
name = "uefi-tpm2"
version = "0.1.0"
edition = "2024"

[dependencies]
hex-slice = "0.1.4"
log = "0.4.28"
uefi = { version = "0.35.0", features = ["logger", "panic_handler"] }
zerocopy = { version = "0.8.27", features = ["derive"] }
