[package]
name = "uefi-tpm2"
version = "0.1.0"
edition = "2024"

[dependencies]
ez_tpm = { version = "0.1.0", path = "../ez_tpm", default-features = false, features = [
    "uefi",
] }
hex-slice = "0.1.4"
log = "0.4.28"
uefi = { version = "0.35.0", features = ["logger", "panic_handler"] }
